/**
 * ShareView.js — Modular View Renderer for Itinerary Export, WhatsApp & Calendar (.ics) Sync
 * (Suggestions #19 & #24 — Fix ICS Calendar Export Date Bug)
 */

function formatItineraryMarkdown(trip, itinerary) {
  const dest = trip.destination || 'India';
  const duration = trip.duration || itinerary.days?.length || 3;
  const travelers = trip.travelers || 2;
  const budget = trip.budgetTier || 'Moderate';

  let md = `# 🗺️ ${dest} Expedition Plan\n\n`;
  md += `**Duration:** ${duration} Days | **Travelers:** ${travelers} | **Budget Tier:** ${budget}\n\n`;

  if (trip.selectedFlight) {
    const f = trip.selectedFlight;
    md += `## ✈️ Flight Details\n`;
    md += `- **Airline:** ${f.airline || f.name} (${f.flightNumber || ''})\n`;
    md += `- **Route:** ${f.from || trip.homeCity || 'Origin'} ➔ ${f.to || dest}\n`;
    md += `- **Departure:** ${f.departureTime || f.time || 'TBD'} | **Arrival:** ${f.arrivalTime || 'TBD'}\n`;
    md += `- **Fare:** ${f.price || f.fare || 'Standard'}\n\n`;
  }

  if (trip.selectedHotel) {
    const h = trip.selectedHotel;
    md += `## 🏨 Lodging\n`;
    md += `- **Property:** ${h.name}\n`;
    md += `- **Type:** ${h.type || 'Boutique Hotel'}\n`;
    md += `- **Location:** ${h.location || dest}\n`;
    md += `- **Nightly Rate:** ${h.price || h.rate || 'Standard'}\n\n`;
  }

  md += `## 📅 Day-by-Day Schedule\n\n`;
  (itinerary.days || []).forEach((d) => {
    md += `### Day ${d.dayNumber}: ${d.title || d.theme || 'Exploration'}\n`;
    (d.stops || []).forEach((s) => {
      md += `- **${s.time || 'Activity'}** — **${s.name}**\n`;
      if (s.why || s.description) md += `  ${s.why || s.description}\n`;
    });
    md += `\n`;
  });

  md += `---\n*Generated by Trailmate AI Travel Planner*\n`;
  return md;
}

/**
 * Generate and download an .ics iCalendar file with real trip start dates.
 * (Suggestion #24 — Fix ICS Calendar Export Date Bug)
 */
export function downloadIcsCalendar(trip = {}, itinerary = {}) {
  const dest = trip.destination || 'Trip';

  // Use actual trip.startDate or parse from dates string
  let baseDate = null;
  if (trip.startDate) {
    const parsed = new Date(trip.startDate);
    if (!isNaN(parsed.getTime())) baseDate = parsed;
  }
  if (!baseDate && trip.dates) {
    const match = String(trip.dates).match(/(\d{4}-\d{2}-\d{2})/);
    if (match) {
      const parsed = new Date(match[1]);
      if (!isNaN(parsed.getTime())) baseDate = parsed;
    }
  }
  if (!baseDate) {
    baseDate = new Date();
    baseDate.setDate(baseDate.getDate() + 1);
  }

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Trailmate//AI Travel Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ];

  (itinerary.days || []).forEach((d, dayIdx) => {
    const dayDate = new Date(baseDate);
    dayDate.setDate(baseDate.getDate() + dayIdx);

    const y = dayDate.getFullYear();
    const m = String(dayDate.getMonth() + 1).padStart(2, '0');
    const day = String(dayDate.getDate()).padStart(2, '0');

    (d.stops || []).forEach((s, sIdx) => {
      let startHour = 9 + sIdx * 2;
      let startMinute = 0;
      if (s.time) {
        const timeMatch = String(s.time).match(/(\d{1,2}):?(\d{2})?\s*(AM|PM)?/i);
        if (timeMatch) {
          let h = parseInt(timeMatch[1], 10);
          const min = parseInt(timeMatch[2] || '0', 10);
          const mer = (timeMatch[3] || '').toUpperCase();
          if (mer === 'PM' && h < 12) h += 12;
          if (mer === 'AM' && h === 12) h = 0;
          startHour = h;
          startMinute = min;
        }
      }

      const hh = String(Math.min(23, startHour)).padStart(2, '0');
      const mm = String(startMinute).padStart(2, '0');
      const endH = String(Math.min(23, startHour + 2)).padStart(2, '0');

      const startStr = `${y}${m}${day}T${hh}${mm}00`;
      const endStr = `${y}${m}${day}T${endH}${mm}00`;

      icsContent.push('BEGIN:VEVENT');
      icsContent.push(`UID:tm-${Date.now()}-${dayIdx}-${sIdx}@trailmate.app`);
      icsContent.push(`DTSTAMP:${y}${m}${day}T000000Z`);
      icsContent.push(`DTSTART:${startStr}`);
      icsContent.push(`DTEND:${endStr}`);
      icsContent.push(`SUMMARY:${(s.name || s.title || 'Sight').replace(/,/g, '\\,')} (${dest})`);
      icsContent.push(`DESCRIPTION:${(s.why || s.description || '').replace(/\n/g, ' ').replace(/,/g, '\\,')}`);
      icsContent.push('END:VEVENT');
    });
  });

  icsContent.push('END:VCALENDAR');

  const blob = new Blob([icsContent.join('\r\n')], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${dest.toLowerCase().replace(/\s+/g, '-')}-itinerary.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function renderShareView(container, { switchView, store }) {
  const { trip = {}, itinerary = null } = store.getState();
  const currDest = trip.destination || 'Your Journey';

  if (!itinerary || !itinerary.days || itinerary.days.length === 0) {
    container.innerHTML = `
      <div class="mb-5">
        <span class="text-[10px] font-mono font-bold tracking-widest uppercase text-[#944a1a] bg-[#944a1a]/10 px-2.5 py-0.5 rounded-full">SHARE &amp; COLLABORATE</span>
        <h1 class="text-[26px] sm:text-[30px] font-bold text-neutral-900 mt-1 font-headline-md tracking-tight">Share Itinerary</h1>
        <p class="text-xs text-neutral-600 font-body-sm">Export and collaborate on your travel plan</p>
      </div>

      <div class="tactile-inset-panel mb-6 text-center py-4">
        <p class="text-xs text-neutral-700">
          Your itinerary for <strong class="text-primary">${currDest}</strong> is still being crafted! Once your stay, flights, and stops are composed, you can export and share it here.
        </p>
      </div>

      <button id="btnReturnFromShare" class="w-full py-3.5 bg-[#8b4513] text-white rounded-xl text-sm font-bold hover:bg-[#703810] transition-all shadow-md active:scale-[0.99] cursor-pointer">
        Continue Planning
      </button>
    `;
    document.getElementById('btnReturnFromShare')?.addEventListener('click', () => switchView('chat'));
    return;
  }

  const md = formatItineraryMarkdown(trip, itinerary);

  container.innerHTML = `
    <div class="mb-5">
      <span class="text-[10px] font-mono font-bold tracking-widest uppercase text-[#944a1a] bg-[#944a1a]/10 px-2.5 py-0.5 rounded-full">SHARE &amp; COLLABORATE</span>
      <h1 class="text-[26px] sm:text-[30px] font-bold text-neutral-900 mt-1 font-headline-md tracking-tight">Share &amp; Export</h1>
      <p class="text-xs text-neutral-600 font-body-sm">Export your <strong class="text-primary">${currDest}</strong> itinerary</p>
    </div>

    <div class="space-y-3">
      <button id="btnCopyMarkdown" class="w-full p-3.5 tactile-inset-panel hover:bg-white text-left flex items-center justify-between transition-colors cursor-pointer group">
        <div>
          <h5 class="font-bold text-xs text-neutral-900">Copy as Markdown</h5>
          <p class="text-[10px] text-neutral-600">Formatted for Notion, Notes, or Markdown docs</p>
        </div>
        <span class="material-symbols-outlined text-neutral-700 text-lg group-hover:translate-x-0.5 transition-transform">content_copy</span>
      </button>

      <button id="btnCopyWhatsapp" class="w-full p-3.5 tactile-inset-panel hover:bg-white text-left flex items-center justify-between transition-colors cursor-pointer group">
        <div>
          <h5 class="font-bold text-xs text-neutral-900">WhatsApp / Message Summary</h5>
          <p class="text-[10px] text-neutral-600">Compact text ready to send travel companions</p>
        </div>
        <span class="material-symbols-outlined text-neutral-700 text-lg group-hover:translate-x-0.5 transition-transform">send</span>
      </button>

      <button id="btnDownloadIcs" class="w-full p-3.5 tactile-inset-panel hover:bg-white text-left flex items-center justify-between transition-colors cursor-pointer group">
        <div>
          <h5 class="font-bold text-xs text-neutral-900">Export to Calendar (.ics)</h5>
          <p class="text-[10px] text-neutral-600">Adds daily stops with real start dates to Apple / Google Calendar</p>
        </div>
        <span class="material-symbols-outlined text-neutral-700 text-lg group-hover:translate-x-0.5 transition-transform">calendar_month</span>
      </button>
    </div>

    <button id="btnReturnFromShare" class="w-full mt-6 py-3.5 bg-[#8b4513] text-white rounded-xl text-sm font-bold hover:bg-[#703810] transition-all shadow-md active:scale-[0.99] cursor-pointer">
      Return to Planner
    </button>
  `;

  document.getElementById('btnCopyMarkdown')?.addEventListener('click', async () => {
    await navigator.clipboard.writeText(md);
    switchView('chat');
    store.pushMessage({ role: 'bot', text: '📋 **Itinerary copied to clipboard!**' });
  });

  document.getElementById('btnCopyWhatsapp')?.addEventListener('click', async () => {
    const shortSummary = `🗺️ *${currDest} Trip Plan*\n\n` + (itinerary.days || []).map(d => `*Day ${d.dayNumber}: ${d.title || d.theme}*\n` + (d.stops || []).map(s => `• ${s.time}: ${s.name}`).join('\n')).join('\n\n') + '\n\n_Planned with Trailmate AI_';
    await navigator.clipboard.writeText(shortSummary);
    switchView('chat');
    store.pushMessage({ role: 'bot', text: '💬 **WhatsApp trip summary copied!**' });
  });

  document.getElementById('btnDownloadIcs')?.addEventListener('click', () => {
    downloadIcsCalendar(trip, itinerary);
    switchView('chat');
    store.pushMessage({ role: 'bot', text: '📅 **Trip calendar (.ics) downloaded!**' });
  });

  document.getElementById('btnReturnFromShare')?.addEventListener('click', () => switchView('chat'));
}
