/**
 * exportUtils.js — Shared utilities for itinerary exporting, markdown formatting,
 * Google Maps directions URL, Google Calendar web links, and .ics generation.
 */

export function formatItineraryMarkdown(trip, itinerary) {
  const dest = trip.destination || 'India';
  const duration = trip.duration || itinerary.days?.length || 3;
  const travelers = trip.travelers || 2;
  const budget = trip.budgetTier || 'Moderate';

  let md = `# 🗺️ ${dest} Expedition Plan\n\n`;
  md += `**Duration:** ${duration} Days | **Travelers:** ${travelers} | **Budget Tier:** ${budget}\n\n`;

  if (trip.selectedFlight) {
    const f = trip.selectedFlight;
    md += `## ✈️ Flight Details\n`;
    md += `- **Airline:** ${f.airline || f.name} (${f.flightNumber || ''})\n`;
    md += `- **Route:** ${f.from || trip.homeCity || 'Origin'} ➔ ${f.to || dest}\n`;
    md += `- **Departure:** ${f.departureTime || f.time || 'TBD'} | **Arrival:** ${f.arrivalTime || 'TBD'}\n`;
    md += `- **Fare:** ${f.price || f.fare || 'Standard'}\n\n`;
  }

  if (trip.selectedHotel) {
    const h = trip.selectedHotel;
    md += `## 🏨 Lodging\n`;
    md += `- **Property:** ${h.name}\n`;
    md += `- **Type:** ${h.type || 'Boutique Hotel'}\n`;
    md += `- **Location:** ${h.location || dest}\n`;
    md += `- **Nightly Rate:** ${h.price || h.rate || 'Standard'}\n\n`;
  }

  md += `## 📅 Day-by-Day Schedule\n\n`;
  (itinerary.days || []).forEach((d) => {
    md += `### Day ${d.dayNumber}: ${d.title || d.theme || 'Exploration'}\n`;
    (d.stops || []).forEach((s) => {
      md += `- **${s.time || 'Activity'}** — **${s.name}**\n`;
      if (s.why || s.description) md += `  ${s.why || s.description}\n`;
    });
    md += `\n`;
  });

  md += `---\n*Generated by Trailmate AI Travel Planner*\n`;
  return md;
}

/**
 * Generate and download an .ics iCalendar file with real trip start dates.
 */
export function downloadIcsCalendar(trip = {}, itinerary = {}) {
  const dest = trip.destination || 'Trip';

  // Use actual trip.startDate or parse from dates string
  let baseDate = null;
  if (trip.startDate) {
    const parsed = new Date(trip.startDate);
    if (!isNaN(parsed.getTime())) baseDate = parsed;
  }
  if (!baseDate && trip.dates) {
    const match = String(trip.dates).match(/(\d{4}-\d{2}-\d{2})/);
    if (match) {
      const parsed = new Date(match[1]);
      if (!isNaN(parsed.getTime())) baseDate = parsed;
    }
  }
  if (!baseDate) {
    baseDate = new Date();
    baseDate.setDate(baseDate.getDate() + 1);
  }

  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Trailmate//AI Travel Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ];

  (itinerary.days || []).forEach((d, dayIdx) => {
    const dayDate = new Date(baseDate);
    dayDate.setDate(baseDate.getDate() + dayIdx);

    const y = dayDate.getFullYear();
    const m = String(dayDate.getMonth() + 1).padStart(2, '0');
    const day = String(dayDate.getDate()).padStart(2, '0');

    (d.stops || []).forEach((s, sIdx) => {
      let startHour = 9 + sIdx * 2;
      let startMinute = 0;
      if (s.time) {
        const timeMatch = String(s.time).match(/(\d{1,2}):?(\d{2})?\s*(AM|PM)?/i);
        if (timeMatch) {
          let h = parseInt(timeMatch[1], 10);
          const min = parseInt(timeMatch[2] || '0', 10);
          const mer = (timeMatch[3] || '').toUpperCase();
          if (mer === 'PM' && h < 12) h += 12;
          if (mer === 'AM' && h === 12) h = 0;
          startHour = h;
          startMinute = min;
        }
      }

      const hh = String(Math.min(23, startHour)).padStart(2, '0');
      const mm = String(startMinute).padStart(2, '0');
      const endH = String(Math.min(23, startHour + 2)).padStart(2, '0');

      const startStr = `${y}${m}${day}T${hh}${mm}00`;
      const endStr = `${y}${m}${day}T${endH}${mm}00`;

      icsContent.push('BEGIN:VEVENT');
      icsContent.push(`UID:tm-${Date.now()}-${dayIdx}-${sIdx}@trailmate.app`);
      icsContent.push(`DTSTAMP:${y}${m}${day}T000000Z`);
      icsContent.push(`DTSTART:${startStr}`);
      icsContent.push(`DTEND:${endStr}`);
      icsContent.push(`SUMMARY:${(s.name || s.title || 'Sight').replace(/,/g, '\\,')} (${dest})`);
      icsContent.push(`DESCRIPTION:${(s.why || s.description || '').replace(/\n/g, ' ').replace(/,/g, '\\,')}`);
      icsContent.push('END:VEVENT');
    });
  });

  icsContent.push('END:VCALENDAR');

  const blob = new Blob([icsContent.join('\r\n')], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${dest.toLowerCase().replace(/\s+/g, '-')}-itinerary.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Generate Google Maps multi-waypoint directions URL
 */
export function getGoogleMapsDirectionsUrl(trip = {}, itinerary = {}) {
  const dest = trip.destination || '';
  const stops = [];
  (itinerary.days || []).forEach(day => {
    (day.stops || []).forEach(s => {
      const name = s.name || s.title;
      if (name) stops.push(`${name}, ${dest}`);
    });
  });

  if (stops.length === 0) {
    return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(dest)}`;
  }

  const origin = encodeURIComponent(stops[0]);
  const destination = encodeURIComponent(stops[stops.length - 1]);
  const waypoints = stops.slice(1, -1).slice(0, 8).map(encodeURIComponent).join('|');

  let url = `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}`;
  if (waypoints) {
    url += `&waypoints=${waypoints}`;
  }
  return url;
}

/**
 * Generate Google Calendar 1-click web event link
 */
export function getGoogleCalendarWebUrl(trip = {}, itinerary = {}) {
  const dest = trip.destination || 'Expedition';
  const title = encodeURIComponent(`${dest} Expedition — Trailmate Plan`);
  const details = encodeURIComponent(
    (itinerary.days || [])
      .map(d => `Day ${d.dayNumber}: ${d.title || d.theme}\n` + (d.stops || []).map(s => `• ${s.time || ''} ${s.name}`).join('\n'))
      .join('\n\n')
  );

  let startDate = new Date();
  if (trip.startDate) {
    const p = new Date(trip.startDate);
    if (!isNaN(p.getTime())) startDate = p;
  }
  const duration = itinerary.days?.length || 3;
  const endDate = new Date(startDate);
  endDate.setDate(startDate.getDate() + duration);

  const formatGCalDate = (d) => d.toISOString().replace(/-|:|\.\d\d\d/g, '').slice(0, 8);
  const dates = `${formatGCalDate(startDate)}/${formatGCalDate(endDate)}`;

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&location=${encodeURIComponent(dest)}&dates=${dates}`;
}
